---
fullname: ExpFloat
shortname: expfloat
organization: thery
community: false
dune: false
action: true

synopsis: e

description: |-

  Exponential in binary 64 

  Progress

  Algorithm P1 : 
  - [Algotiyhm P1](./algoP1.v#L358-L366)
  - [Absolute error of Sollya polynomial](./algoP1.v#L151-L152)
  - [Relative error of Sollya polynomial](./algoP1.v#L340-L342)
  - [Bound of `ph` of algorithm P1](./algoP1.v#L1669-L1674)
  - [Bound of `pl` of algorithm P1](./algoP1.v#L1691-L11696)
  - [Absolute error of algorithm P1](./algoP1.v#L1702-L1707)
  - [Relative error of algorithm P1](./algoP1.v#L1713-L1719)
  - [Refined relative error of algorithm P1](./algoP1.v#L1726-L1732)

  Algorithm Log1 :
  - [Definition of the `INVERSE` table](./tableINVERSE.v#L48-L79)
  - [Lemma 3](./tableINVERSE.v#L284-L289)   
  - [Definition of the `LOGINV` table](./tableLOGINV.v#L108-L292)
  - [Definition of Log1](./algoLog1.v#L110-L121)
authors:
- name: Laurent Théry
- name: Laurence Rideau

maintainers:
- name: Laurent Théry
  nickname: thery
- name: Laurence Rideau
  nickname: lrg

opam-file-maintainer: thery@sophia.inria.fr

license:
  fullname: MIT License
  identifier: MIT

supported_coq_versions:
  text: '8.17 or later'
  opam: '{(>= "8.17")}'

dependencies:
- opam:
    name: coq-mathcomp-ssreflect
    version: '{(>= "1.17.0")}'
  description: |-
    [MathComp ssreflect 1.17 or later](https://math-comp.github.io)

- opam:
    name: coq-coquelicot
    version: '{(>= "3.3.1")}'
  description: |-
    [Coquelicot 3.3.1 or later](https://gitlab.inria.fr/coquelicot/coquelicot)

- opam:
    name: coq-mathcomp-algebra
    version: '{(>= "1.17.0")}'
  description: |-
    [MathComp algebra 1.17 or later](https://math-comp.github.io)

- opam:
    name: coq-flocq
    version: '{(>= "4.1.1")}'
  description: |-
    [Flocq 4.1.1 or later](https://gitlab.inria.fr/flocq/flocq)

- opam:
    name: coq-interval
    version: '{(>= "4.7.0")}'
  description: |-
    [Interval 4.7.0 or later](https://gitlab.inria.fr/coqinterval/interval)


tested_coq_opam_versions:
- version: '1.17.0-coq-8.17'
  repo: 'mathcomp/mathcomp'

namespace: floatexp

keywords:
- name: floating point number
- name: exponential function
- name: Coq




---