---
fullname: ExpFloat
shortname: expfloat
organization: thery
community: false
dune: false
action: true

synopsis: e

description: |-

  Exponential in binary 64 

  Progress

  Algorithm FastTwoSum : 
  - [Bounds on the error of FastTwoSum](./Fast2Sum_robust_flt.v#L946-L953)

  Algorithm P1 : 
  - [Algotiyhm P1](./algoP1.v#L356-L364)
  - [Absolute error of Sollya polynomial](./algoP1.v#L150-L151)
  - [Relative error of Sollya polynomial](./algoP1.v#L338-L340)
  - [Bound of `ph` of algorithm P1](./algoP1.v#L1710-L1715)
  - [Bound of `pl` of algorithm P1](./algoP1.v#L1732-L1737)
  - [Absolute error of algorithm P1](./algoP1.v#L1743-L1748)
  - [Relative error of algorithm P1](./algoP1.v#L1754-L1760)
  - [Refined relative error of algorithm P1](./algoP1.v#L1767-L1773)

  Algorithm Log1 :
  - [Definition of the `INVERSE` table](./tableINVERSE.v#L47-L78)
  - [Lemma 3](./tableINVERSE.v#L192-L197)   
  - [Definition of the `LOGINV` table](./tableLOGINV.v#L107-L291)
  - [Definition of Log1](./algoLog1.v#L227-L238)
  - [Lemma 4](./algoLog1.v#L2508-L2514)

  Algorithm Mul1 :
  - [Definition of Mul1](./algoMul1.v#L67-L70)
  - [Lemma 5](./algoMul1.v#L73-L84)

  Algorithm Q1 :
  - [Definition of the polynomial Q](./algoQ1.v#L127-L128)
  - [Absolute error of the polynomial Q](./algoQ1.v#L130-L132)
  - [Algorithm Q1](./algoQ1.v#L140-L144)
  - [Lemma 6](./algoQ1.v#L148-L153)

  Algorithm Exp1 :
  - [table T1](./tableT1.v#L76-L142)
  - [relative error for T1](./tableT1.v#L208-L211)
  - [table T2](./tableT2.v#L76-L142)
  - [relative error for T2](./tableT2.v#L209-L212)
  - [algorithm Exp1](./algoExp1.v#L1848-L1876)
  - [Lemma 7](./algoExp1.v#L1893-L1901)

  Algorithm Phase1 :
  - [algorithm Phase 1](./algoPhase1.v#L2144-L2154)
  - [Theorem 1](./algoPhase1.v#L2158-L2160)

authors:
- name: Laurent Théry
- name: Laurence Rideau

maintainers:
- name: Laurent Théry
  nickname: thery
- name: Laurence Rideau
  nickname: lrg

opam-file-maintainer: thery@sophia.inria.fr

license:
  fullname: MIT License
  identifier: MIT

supported_coq_versions:
  text: '8.18 or later'
  opam: '{(>= "8.18")}'

dependencies:
- opam:
    name: coq-mathcomp-ssreflect
    version: '{(>= "1.17.0")}'
  description: |-
    [MathComp ssreflect 1.17 or later](https://math-comp.github.io)

- opam:
    name: coq-coquelicot
    version: '{(>= "3.4.0")}'
  description: |-
    [Coquelicot 3.4.0 or later](https://gitlab.inria.fr/coquelicot/coquelicot)

- opam:
    name: coq-mathcomp-algebra
    version: '{(>= "1.17.0")}'
  description: |-
    [MathComp algebra 1.17 or later](https://math-comp.github.io)

- opam:
    name: coq-flocq
    version: '{(>= "4.1.3")}'
  description: |-
    [Flocq 4.1.3 or later](https://gitlab.inria.fr/flocq/flocq)

- opam:
    name: coq-interval
    version: '{(>= "4.8.1")}'
  description: |-
    [Interval 4.8.1 or later](https://gitlab.inria.fr/coqinterval/interval)


tested_coq_opam_versions:
- version: '1.17.0-coq-8.18'
  repo: 'mathcomp/mathcomp'

namespace: floatexp

keywords:
- name: floating point number
- name: exponential function
- name: Coq




---